#ifndef BOOK_MANAGEMENT_GUARD__H
#define BOOK_MANAGEMENT_GUARD__H

#include <stdio.h>

/*You can extend the structs (Book and BookList) defined in this head file;
  However, you may not change the function prototypes.
  You are also free to add additional head files and data structures as needed.
*/


typedef struct _Book {
	    int id; //Book ID
		char *title; //book title
		char *authors; //comma separated list of authors
		int year; // year of publication
		int copies; //number of copies the library has
}Book;

typedef struct _BookList {
	 unsigned int length; // number of elements in the (Book*) List
	 struct _Book Book;
	 struct _BookList *next; //pointer to the next book element
}BookList;

Book *init_book_list();

//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file);

//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file);

//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book();

//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book();

void Search();
void Display();
#endif
