#include <stdio.h>
#include <ctype.h>
#include "menu.h"
#include "user.h"
#include "librarian.h"
#include "book_management.h"

Book *book;
BookList *books;
Book *init_book_list()
{
    struct Book *head;
    head = (struct Book *)malloc(sizeof(Book));
    return head;
}


//saves the database of books in the specified file
//returns 0 if books were stored correctly, or an error code otherwise
int store_books(FILE *file){

    // write books to books.txt
    file = fopen("../books.txt", "w+");
    BookList *p = books->next;
    for (int i = 0; i < books->length; i++)
    {
        fprintf(file, "%d|%s|%s|%d|%d\n", p->Book.id, p->Book.title, p->Book.authors, p->Book.year, p->Book.copies);
        p = p->next;
    }
    fprintf(file, "%d|%s|%s|%d|%d", p->Book.id, p->Book.title, p->Book.authors, p->Book.year, p->Book.copies);
    fclose(file);
}

//loads the database of books from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if books were loaded correctly, or an error code otherwise
int load_books(FILE *file){
    books = init_book_list();
    file = fopen("books.txt", "r");
    if (file == NULL)
    {
        exit(0);
    }
    BookList *p, *pre = books;
    char c;
    char tmp[100];
    memset(tmp, '\0', 100);
    int j = 0, k = 1;
    int count = -1;
    while (!feof(file))
    {
        p = (BookList *)malloc(sizeof(BookList));
        do
        {
            c = fgetc(file);
            if (c != '|' && c != '\n' && !feof(file))
            {
                tmp[j] = c;
                j++;
            }
            else if (c == '|' || c == '\n' || feof(file))
            {
                if (k == 1)
                {
                    char id[10];
                    strcpy(id, tmp);
                    p->Book.id = atoi(id);
                }
                else if (k == 2)
                {
                    p->Book.title = (char *)malloc(sizeof(char) * strlen(tmp));
                    strcpy(p->Book.title, tmp);
                }
                else if (k == 3)
                {
                    p->Book.authors = (char *)malloc(sizeof(char) * strlen(tmp));
                    strcpy(p->Book.authors, tmp);
                }
                else if (k == 4)
                {
                    char year[10];
                    strcpy(year, tmp);
                    p->Book.year = atoi(year);
                }
                else if (k == 5)
                {
                    char copies[10];
                    strcpy(copies, tmp);
                    p->Book.copies = atoi(copies);
                }
                j = 0;
                k++;
                memset(tmp, '\0', 100);
            }
        } while (c != '\n' && !feof(file));
        k = 1;
        p->next = NULL;
        pre->next = p;
        count++;
        pre = p;
    }
    books->length = count;

    // display_all_books();

    fclose(file);
}

//adds a book to the ones available to the library
//returns 0 if the book could be added, or an error code otherwise
int add_book(){
    BookList *p, *pre = books;
    p = (BookList *)malloc(sizeof(BookList));
    char tmp[100];
    printf("Enter the title of the book you wish to add: ");
    memset(tmp, '\0', 100);
    gets(tmp);
    p->Book.title = (char *)malloc(sizeof(strlen(tmp)));
    strcpy(p->Book.title, tmp);
    printf("Enter the author of the book you wish to add: ");
    memset(tmp, '\0', 100);
    gets(tmp);
    if (tmp>=0 && tmp<=9){
        printf("Sorry, the author name you entered is invalid.");
        add_book();
    }
    p->Book.authors = (char *)malloc(sizeof(strlen(tmp)));
    strcpy(p->Book.authors, tmp);
    printf("Enter the year that the book you wish to add was release: ");
    scanf("%d", &p->Book.year);
    getchar();
    printf("Enter the number of copies of the book that you wish to add: ");
    scanf("%d", &p->Book.copies);
    getchar();
    books->length++;

    p->Book.id = books->length + 1;

    while (pre->next != NULL)
    {
        pre = pre->next;
    }
    pre->next = p;
    p->next = NULL;
    printf("add successfully\n");
    // printf("Sorry,you attempted to add an invalid book,please try again.\n");
}

//removes a book from the library
//returns 0 if the book could be successfully removed, or an error code otherwise.
int remove_book(){
    int id;
    printf("Enter the id of the book you wish to remove: ");
    scanf("%d", &id);
    getchar();
    BookList *p = books->next, *pre = books;
    while (p != NULL)
    {
        if (p->Book.id == id)
        {
            pre->next = p->next;
            free(p);
            // p = pre->next;
            books->length--;
            break;
        }
        else
        {
            pre = p;
            p = p->next;
        }
    }

    printf("remove successfully\n");
}

void Search()
{
    int num;
    while (1)
    {

        printf("Please choose an option:\n");
        printf("1) Find books by title\n");
        printf("2) Find books by author\n");
        printf("3) Find books by year\n");
        printf("4) Return to previous menu\n Option: ");
        scanf("%d", &num);
        getchar();
        BookList *p = books;
        if (num == 1)
        {
            char title[100];
            printf("Please enter title: ");
            gets(title);
            printf("ID\tTitle\tAuthor\tyear\tcopies\n");
            while (p->next != NULL)
            {
                p = p->next;
                if (p != NULL && strcmp(p->Book.title, title) == 0)
                {
                    printf("%d \t%s \t%s \t%d \t%d\n", p->Book.id, p->Book.title, p->Book.authors, p->Book.year, p->Book.copies);
                }
            }
        }
        if (num == 2)
        {
            char author[100];
            printf("Please enter author: ");
            gets(author);
            printf("ID\tTitle\tAuthor\tyear\tcopies\n");
            while (p->next != NULL)
            {
                p = p->next;
                if (p != NULL && strcmp(p->Book.authors, author) == 0)
                {
                    printf("%d \t%s \t%s \t%d \t%d\n", p->Book.id, p->Book.title, p->Book.authors, p->Book.year, p->Book.copies);
                }
            }
        }
        if (num == 3)
        {
            int year;
            printf("Please enter year: ");
            scanf("%d", &year);
            getchar();
            printf("ID\tTitle\tAuthor\tyear\tcopies\n");
            while (p->next != NULL)
            {
                p = p->next;
                if (p != NULL && p->Book.year == year)
                {
                    printf("%d \t%s \t%s \t%d \t%d\n", p->Book.id, p->Book.title, p->Book.authors, p->Book.year, p->Book.copies);
                }
            }
        }
        if (num == 4)
        {
            break;
        }
        else
        {
        }
    }
}

void Display()
{
    BookList *p = books->next;
    printf("ID\tTitle\tAuthor\tyear\tcopies\n");
    while (p != NULL)
    {
        printf("%d \t%s \t%s \t%d \t%d\n", p->Book.id, p->Book.title, p->Book.authors, p->Book.year, p->Book.copies);
        p = p->next;
    }
}


